### ISSUE TITLE
Could work with 600 series?

### ISSUE THREAD

**Issue by Salsalove** [DeebotUniverse/Deebot-4-Home-Assistant#215]
### Question

After Ha 2022.7 all the ecovacs integrations are broken (custom and "official"). Could deebot-4-home-assistant work with 600 series and other older versions?

**Comment by mrbungle64** [comment]
@Salsalove 

The Deebot 600 series is currently not supported by the deebot-client library (used by Deebot for Home Assistant)
https://deebot.readthedocs.io/home/faq/
https://deebot.readthedocs.io/home/models/#deebot-client
because it uses a different protocol for communication.

But you can install the [Node-RED add-on](https://github.com/hassio-addons/addon-node-red) and use [Ecovacs Deebot node for Node-RED](https://github.com/mrbungle64/node-red-contrib-ecovacs-deebot).

**Comment by Salsalove** [comment]
> @Salsalove
> 
> The Deebot 600 series is currently not supported by the deebot-client library (used by Deebot for Home Assistant) https://deebot.readthedocs.io/home/faq/ https://deebot.readthedocs.io/home/models/#deebot-client because it uses a different protocol for communication.
> 
> But you can install the [Node-RED add-on](https://github.com/hassio-addons/addon-node-red) and use [Ecovacs Deebot node for Node-RED](https://github.com/mrbungle64/node-red-contrib-ecovacs-deebot).

thanks...I'll try it!
