### ISSUE TITLE
Setup blanks after configuration

### ISSUE THREAD

**Issue by thegreekgeek** [DeebotUniverse/Deebot-4-Home-Assistant#240]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

Hey all, so I've been trying to get this integration set up since deebot for home assistant went away, and I've been having a hell of a time. I've got an Ecovacs n79s and I've had most of the integrations installed at some point and I've cleaned up my config.yaml of all deebot and ecovacs references (commented out on config.yaml, didn't get rid of ecovacs,yaml or deebot.yaml).

On installation of the integration I enter all my relevant info (email instead of shortid, also tried NA and WW) and on submitting them I get this:
![GsB6Npq](https://user-images.githubusercontent.com/463784/187234876-ac6962cb-5b1b-4789-9a19-c79728d3d962.png)

I've enabled the debug logging, but I can't seem to find anything related to the component. 
Any Ideas?

### On which deebot vacuum you have the issue?

Ecovacs n79s

### Which version of the Deebot component are you using?

1.4.1

### Which version of Home Assistant are you using?

2022.8.6

### What type of installation are you running?

Home Assistant Container

### Country

us

### Continent

ww/na

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```txt
Logs didn't show anything, not sure if it's because it hasn't been set up completely?
```

**Comment by mrbungle64** [comment]
@thegreekgeek 

Deebot N79 series is not supported by the deebot-client library (used by Deebot for Home Assistant)
https://deebot.readthedocs.io/home/faq/
https://deebot.readthedocs.io/home/models/#deebot-client
because it uses a different protocol for communication.

But you can install the [Node-RED add-on](https://github.com/hassio-addons/addon-node-red) and use [Ecovacs Deebot node for Node-RED](https://github.com/mrbungle64/node-red-contrib-ecovacs-deebot).
