### ISSUE TITLE
Is development/bug fixing on this integration abandoned?

### ISSUE THREAD

**Issue by jayscovill** [DeebotUniverse/Deebot-4-Home-Assistant#276]
### Question

Just wondering if development or bug fixes on this integration is have been abandoned.

Seems like there are issues still open that are no longer being worked on and left to go stale. A glaring one is the integration no longer receiving status updates for the vacuum and no history being recorded in Home Assistant.  Even restarting the integration daily doesn't fix the problem anymore.

I'd be happy to try and provide more information to get this one addressed as it has a major impact on the usability of the integration.  I've turned on debug logging and haven't seen a lot of helpful log entries but if the owner can provide any more direction on capturing more helpful logs I'm happy to help.

**Comment by edenhaus** [comment]
Hi,

this integration is maintain by me for free in my free time. As I'm a student and I have nothing to do with ecovacs it is hard to implement new features from the new models.
Also I cannot reproduce the bus that are still open.
My vacuum (Ozmo 950) is working perfectly without any problems with this integration.

As ecovacs has no public api and I cannot afford to buy me the new X1 some issues will remain open until someone is providing more information and is analyzing the traffic between the app and the ecovacs servers.
I know there exists V2 commands, but as my model doesn't support it is hard to debug or even implement it for me.

If you have the skills please capture the traffic between the app with a man in the middle proxy. Or you can also fund me that I can buy me the new model. This integration will be always free but as it has nothing to do with ecovacs I also have no access to their internal documentation or the give me some budget.

Feel free to ask me anything and with your help maybe we can solve some issue 😊

The development stopped or at least slowed down since the summer as I got seriously injured in summer and still struggling with the aftermath (no sport, each day different medicine). The real life hase priority

**Comment by Nismonx** [comment]
Would wireshark be good enough to capture the data needed ?

**Comment by joshnl1977** [comment]
I've got the X1 Omni and would love to help out. You mention capturing the traffic, but I don't know how to do that. Would you be able to provide some info on how to do that?

**Comment by edenhaus** [comment]
Depending your technical skills...

You need to spin up a man in the middle proxy and install their certificates on your device. Than trust this certificate (depends on your device OS).
Afterwards you can capture the whole traffic.
**Attention all traffic is captured. So don't post it somewhere without.analysis**

I leave it a little bit abstract as it depends a lot howyou set it up. Woth docker or not
