### ISSUE TITLE
configuration ?

### ISSUE THREAD

**Issue by JeedHome44** [DeebotUniverse/Deebot-4-Home-Assistant#277]
### Question

Hello,
Sorry i'm french and i have a bad english

I juste receive a Deebot Ecovacs X1 e Omni.
I want to use this github. I place the deebot folder in custom_components.

I don't find what i have to write in configuration.yaml ine README file.
Can you help me please?

**Comment by Nismonx** [comment]
Are you following the instructions from this [LINK](https://deebot.readthedocs.io/integrations/home-assistant/)  ?

Also you have to keep in mind that Homeassistant have changed a few things in the way configuration.yaml works, a good portion of the script needs to go on to script.yaml.

The way Automations works have changed quite a bit since the writing of the above tutorials. If you don't have any Automation yet then you should be fine as home assistant will convert it for you.

To start with you need to install Studio code server or something similar.

Try to Google ' how to edit configuration.yaml '

This should work well after you change the vacuum name to yours
[https://deebot.readthedocs.io/integrations/home-assistant/examples/ui/simple/](url)

**Comment by JeedHome44** [comment]
It's ok. It works but never refresh statut ?

**Comment by Nismonx** [comment]
> It's ok. It works but never refresh statut ?

Yes, we all having the same issues with the X1
#268

**Comment by JeedHome44** [comment]
No way to control it in local ?
