### ISSUE TITLE
stopReason KeyError

### ISSUE THREAD

**Issue by rothnic** [DeebotUniverse/Deebot-4-Home-Assistant#63]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Found another error in the Home Assistant logs. I was trying different things and ended up running out of battery, so the vacuum decided to go back to the dock to charge. I think this is when the `KeyError: stopReason` occurred.

The only other factor here was that I was noticing the map not updating, so I setup an automation to manually refresh the map while the vacuum is in the Cleaning state, every 1 minute. I'm not sure if that refresh call triggered this or the returning to the dock, or maybe a combination of the two.

### On which deebot vacuum you have the issue?

DEEBOT OZMO T8+

### Which version of the Deebot component are you using?

0.2.0

### Which version of Home Assistant are you using?

2021.11.5

### What type of installation are you running?

Home Assistant Core

### Country

us

### Continent

na

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:98
First occurred: 1:32:21 PM (2 occurrences)
Last logged: 1:34:20 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/events/event_bus.py", line 148, in _call_refresh_function
    await self._execute_command(commands[0])
  File "/usr/local/lib/python3.9/site-packages/deebot_client/vacuum_bot.py", line 94, in execute_command
    result = command.handle_requested(self.events, response)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/clean_logs.py", line 37, in handle_requested
    stop_reason=CleanJobStatus(int(log["stopReason"])),
KeyError: 'stopReason'
```
Not sure if this is related, but shortly after there is this error. I assume it is just a result of the previous error

```
Logger: homeassistant
Source: runner.py:98
First occurred: 1:54:06 PM (2 occurrences)
Last logged: 1:54:06 PM

Error doing job: Unclosed connection
```

**Comment by edenhaus** [comment]
Can you please add debug logs or at least the response message. Without I cannot fix the problem as I only know that `stopreason` was missing.

**Comment by rothnic** [comment]
> Can you please add debug logs or at least the response message. Without I cannot fix the problem as I only know that `stopreason` was missing.

Sure, I'll enable logging and see if I can trigger it again.

**Comment by rothnic** [comment]
Ok, so I managed to deplete my battery with logging enabled, and it somehow didn't trigger the same issue. Is there anything you can think of that might cause the wrong message to get to the point of code I highlighted previously. Or, other things to look into?

**Comment by edenhaus** [comment]
You have a newer robot than my one (950).
Your robot has more features and so it can be a lot....

The only idea I have is to leave the debug logs enabled and maybe the error is raised again.

In the meantime I close the issue. Open it again if you have logs 😊

**Comment by andker87** [comment]
Hi, same error since many weeks. This is what happens on startup with debug log (nothing different from what was previously posted here)


``2022-03-28 11:23:05 DEBUG (MainThread) [custom_components.deebot.hub] New vacbot found: XXXXXXXXXXXXXXX``
``2022-03-28 11:23:05 DEBUG (MainThread) [custom_components.deebot.hub] Hub setup complete``
``2022-03-28 11:23:06 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved``
``Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/deebot_client/events/event_bus.py", line 138, in _call_refresh_function
await self._execute_command(commands[0])
File "/usr/local/lib/python3.9/site-packages/deebot_client/vacuum_bot.py", line 111, in execute_command
result = command.handle_requested(self.events, response)
File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/clean_logs.py", line 37, in handle_requested
stop_reason=CleanJobStatus(int(log["stopReason"])),
KeyError: 'stopReason'``


Can I help in any other way to figure out how to fix it?

**Comment by edenhaus** [comment]
If you enable debug logs, each request will be logged and so we can see what response are you getting instead

**Comment by cagnulein** [comment]
same issue and releated to #225

**Comment by cagnulein** [comment]
@edenhaus ;)
